### ISSUE TITLE
--code crashar nuförtiden

### ISSUE THREAD

**Issue by emilhem** [Hagmar/Helix#1]
De uppdaterade spelet den 8 maj. Kan ha och göra med det.

**Comment by Hagmar** [comment]
Tack för heads up! Ska kolla vad de har ändrat och fixa så snart som möjligt. Vore ju hemskt om man tvingades stå i kö

**Comment by emilhem** [comment]
Frågan är om man fortfarande kan använda den? Man får ju svar och allt men man måste ju gå till personalen för att få lappen för expresskassan. Dessutom så tilldelas en biljett varje 15 minuter enligt deras skärmar.

**Comment by Hagmar** [comment]
Hur menar du? Om man samlar på sig några vinster så är det bara att gå och plocka ut alla expressbiljetter på en gång. Om man ska vara schysst så kan man plocka sina vinster på natten när ingen står i kö, så sabbar man inte för den som egentligen leder
